name: mqtt-ppm

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
  # release:
    # types: [published]

env:
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  SERVERCHAN_SCKEY: true
  TZ: Asia/Shanghai


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build Action for ESP-IDF
      uses: Sandiep/ESP_IDF_Build@V1
      with:
        esp_idf_version: v4.4
        target: esp32
        path: 'examples/xyz'


